//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace KlonsA.Classes
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NM_e_gramatinas
    {

        private NM_e_gramatinasPamatdati pamatdatiField;

        private NM_e_gramatinasGigv[] gigvField;

        /// <remarks/>
        public NM_e_gramatinasPamatdati pamatdati
        {
            get
            {
                return this.pamatdatiField;
            }
            set
            {
                this.pamatdatiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gigv")]
        public NM_e_gramatinasGigv[] gigv
        {
            get
            {
                return this.gigvField;
            }
            set
            {
                this.gigvField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NM_e_gramatinasPamatdati
    {

        private long nmr_kodsField;

        private string isais_nosaukField;

        private sbyte gramatinasField;

        private string periods_noField;

        private string periods_lidzField;

        private string gramatinas_iesniedzejsField;

        private System.DateTime izpildes_laiksField;

        /// <remarks/>
        public long nmr_kods
        {
            get
            {
                return this.nmr_kodsField;
            }
            set
            {
                this.nmr_kodsField = value;
            }
        }

        /// <remarks/>
        public string isais_nosauk
        {
            get
            {
                return this.isais_nosaukField;
            }
            set
            {
                this.isais_nosaukField = value;
            }
        }

        /// <remarks/>
        public sbyte gramatinas
        {
            get
            {
                return this.gramatinasField;
            }
            set
            {
                this.gramatinasField = value;
            }
        }

        /// <remarks/>
        public string periods_no
        {
            get
            {
                return this.periods_noField;
            }
            set
            {
                this.periods_noField = value;
            }
        }

        /// <remarks/>
        public string periods_lidz
        {
            get
            {
                return this.periods_lidzField;
            }
            set
            {
                this.periods_lidzField = value;
            }
        }

        /// <remarks/>
        public string gramatinas_iesniedzejs
        {
            get
            {
                return this.gramatinas_iesniedzejsField;
            }
            set
            {
                this.gramatinas_iesniedzejsField = value;
            }
        }

        /// <remarks/>
        public System.DateTime izpildes_laiks
        {
            get
            {
                return this.izpildes_laiksField;
            }
            set
            {
                this.izpildes_laiksField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NM_e_gramatinasGigv
    {

        private long pers_kodsField;

        private string vards_uzvardsField;

        private string numurs_regField;

        private System.DateTime datums_izdField;

        private System.DateTime datums_noField;

        private System.DateTime datums_lidzField;

        private bool datums_lidzFieldSpecified;

        private System.DateTime datums_ierField;

        private NM_e_gramatinasGigvApgadajamais[] apgadajamieField;

        private NM_e_gramatinasGigvPensijas pensijasField;

        private NM_e_gramatinasGigvPapildu_atvieglojumi papildu_atvieglojumiField;

        private NM_e_gramatinasGigvPazime_progr_iin_likmes pazime_progr_iin_likmesField;

        private NM_e_gramatinasGigvPrognozetais_mnm[] prognozetie_mnmField;

        /// <remarks/>
        public long pers_kods
        {
            get
            {
                return this.pers_kodsField;
            }
            set
            {
                this.pers_kodsField = value;
            }
        }

        /// <remarks/>
        public string vards_uzvards
        {
            get
            {
                return this.vards_uzvardsField;
            }
            set
            {
                this.vards_uzvardsField = value;
            }
        }

        /// <remarks/>
        public string numurs_reg
        {
            get
            {
                return this.numurs_regField;
            }
            set
            {
                this.numurs_regField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_izd
        {
            get
            {
                return this.datums_izdField;
            }
            set
            {
                this.datums_izdField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_no
        {
            get
            {
                return this.datums_noField;
            }
            set
            {
                this.datums_noField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_lidz
        {
            get
            {
                return this.datums_lidzField;
            }
            set
            {
                this.datums_lidzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datums_lidzSpecified
        {
            get
            {
                return this.datums_lidzFieldSpecified;
            }
            set
            {
                this.datums_lidzFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_ier
        {
            get
            {
                return this.datums_ierField;
            }
            set
            {
                this.datums_ierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("apgadajamais", IsNullable = false)]
        public NM_e_gramatinasGigvApgadajamais[] apgadajamie
        {
            get
            {
                return this.apgadajamieField;
            }
            set
            {
                this.apgadajamieField = value;
            }
        }

        /// <remarks/>
        public NM_e_gramatinasGigvPensijas pensijas
        {
            get
            {
                return this.pensijasField;
            }
            set
            {
                this.pensijasField = value;
            }
        }

        /// <remarks/>
        public NM_e_gramatinasGigvPapildu_atvieglojumi papildu_atvieglojumi
        {
            get
            {
                return this.papildu_atvieglojumiField;
            }
            set
            {
                this.papildu_atvieglojumiField = value;
            }
        }

        /// <remarks/>
        public NM_e_gramatinasGigvPazime_progr_iin_likmes pazime_progr_iin_likmes
        {
            get
            {
                return this.pazime_progr_iin_likmesField;
            }
            set
            {
                this.pazime_progr_iin_likmesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("prognozetais_mnm", IsNullable = false)]
        public NM_e_gramatinasGigvPrognozetais_mnm[] prognozetie_mnm
        {
            get
            {
                return this.prognozetie_mnmField;
            }
            set
            {
                this.prognozetie_mnmField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NM_e_gramatinasGigvApgadajamais
    {

        private string vards_uzvardsField;

        private string veidsField;

        private System.DateTime datums_noField;

        private System.DateTime datums_lidzField;

        private bool datums_lidzFieldSpecified;

        private System.DateTime datums_ierField;

        /// <remarks/>
        public string vards_uzvards
        {
            get
            {
                return this.vards_uzvardsField;
            }
            set
            {
                this.vards_uzvardsField = value;
            }
        }

        /// <remarks/>
        public string veids
        {
            get
            {
                return this.veidsField;
            }
            set
            {
                this.veidsField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_no
        {
            get
            {
                return this.datums_noField;
            }
            set
            {
                this.datums_noField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_lidz
        {
            get
            {
                return this.datums_lidzField;
            }
            set
            {
                this.datums_lidzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datums_lidzSpecified
        {
            get
            {
                return this.datums_lidzFieldSpecified;
            }
            set
            {
                this.datums_lidzFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_ier
        {
            get
            {
                return this.datums_ierField;
            }
            set
            {
                this.datums_ierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NM_e_gramatinasGigvPensijas
    {

        private NM_e_gramatinasGigvPensijasPensija pensijaField;

        /// <remarks/>
        public NM_e_gramatinasGigvPensijasPensija pensija
        {
            get
            {
                return this.pensijaField;
            }
            set
            {
                this.pensijaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NM_e_gramatinasGigvPensijasPensija
    {

        private string veidsField;

        private System.DateTime datums_noField;

        private System.DateTime datums_lidzField;

        private bool datums_lidzFieldSpecified;

        private System.DateTime datums_ierField;

        /// <remarks/>
        public string veids
        {
            get
            {
                return this.veidsField;
            }
            set
            {
                this.veidsField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_no
        {
            get
            {
                return this.datums_noField;
            }
            set
            {
                this.datums_noField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_lidz
        {
            get
            {
                return this.datums_lidzField;
            }
            set
            {
                this.datums_lidzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datums_lidzSpecified
        {
            get
            {
                return this.datums_lidzFieldSpecified;
            }
            set
            {
                this.datums_lidzFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_ier
        {
            get
            {
                return this.datums_ierField;
            }
            set
            {
                this.datums_ierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NM_e_gramatinasGigvPapildu_atvieglojumi
    {

        private NM_e_gramatinasGigvPapildu_atvieglojumiPapildu_atvieglojums papildu_atvieglojumsField;

        /// <remarks/>
        public NM_e_gramatinasGigvPapildu_atvieglojumiPapildu_atvieglojums papildu_atvieglojums
        {
            get
            {
                return this.papildu_atvieglojumsField;
            }
            set
            {
                this.papildu_atvieglojumsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NM_e_gramatinasGigvPapildu_atvieglojumiPapildu_atvieglojums
    {

        private string veidsField;

        private System.DateTime datums_noField;

        private System.DateTime datums_lidzField;

        private bool datums_lidzFieldSpecified;

        private System.DateTime datums_ierField;

        /// <remarks/>
        public string veids
        {
            get
            {
                return this.veidsField;
            }
            set
            {
                this.veidsField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_no
        {
            get
            {
                return this.datums_noField;
            }
            set
            {
                this.datums_noField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_lidz
        {
            get
            {
                return this.datums_lidzField;
            }
            set
            {
                this.datums_lidzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datums_lidzSpecified
        {
            get
            {
                return this.datums_lidzFieldSpecified;
            }
            set
            {
                this.datums_lidzFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_ier
        {
            get
            {
                return this.datums_ierField;
            }
            set
            {
                this.datums_ierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NM_e_gramatinasGigvPazime_progr_iin_likmes
    {

        private NM_e_gramatinasGigvPazime_progr_iin_likmesPazime_progr_iin_likme pazime_progr_iin_likmeField;

        /// <remarks/>
        public NM_e_gramatinasGigvPazime_progr_iin_likmesPazime_progr_iin_likme pazime_progr_iin_likme
        {
            get
            {
                return this.pazime_progr_iin_likmeField;
            }
            set
            {
                this.pazime_progr_iin_likmeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NM_e_gramatinasGigvPazime_progr_iin_likmesPazime_progr_iin_likme
    {

        private string veidsField;

        private System.DateTime datums_noField;

        private System.DateTime datums_lidzField;

        private bool datums_lidzFieldSpecified;

        private System.DateTime datums_ierField;

        /// <remarks/>
        public string veids
        {
            get
            {
                return this.veidsField;
            }
            set
            {
                this.veidsField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_no
        {
            get
            {
                return this.datums_noField;
            }
            set
            {
                this.datums_noField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_lidz
        {
            get
            {
                return this.datums_lidzField;
            }
            set
            {
                this.datums_lidzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datums_lidzSpecified
        {
            get
            {
                return this.datums_lidzFieldSpecified;
            }
            set
            {
                this.datums_lidzFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_ier
        {
            get
            {
                return this.datums_ierField;
            }
            set
            {
                this.datums_ierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NM_e_gramatinasGigvPrognozetais_mnm
    {

        private string veidsField;

        private System.DateTime datums_noField;

        private System.DateTime datums_lidzField;

        private bool datums_lidzFieldSpecified;

        private System.DateTime datums_ierField;

        private float summaField;

        /// <remarks/>
        public string veids
        {
            get
            {
                return this.veidsField;
            }
            set
            {
                this.veidsField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_no
        {
            get
            {
                return this.datums_noField;
            }
            set
            {
                this.datums_noField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_lidz
        {
            get
            {
                return this.datums_lidzField;
            }
            set
            {
                this.datums_lidzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datums_lidzSpecified
        {
            get
            {
                return this.datums_lidzFieldSpecified;
            }
            set
            {
                this.datums_lidzFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime datums_ier
        {
            get
            {
                return this.datums_ierField;
            }
            set
            {
                this.datums_ierField = value;
            }
        }

        /// <remarks/>
        public float summa
        {
            get
            {
                return this.summaField;
            }
            set
            {
                this.summaField = value;
            }
        }
    }


}